esphome:
  includes:
    - my_cover.h

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Temperatura corridoio"
    humidity:
      name: "Umidità corridoio"
    update_interval: 60s


cover:
- platform: custom
  lambda: |-
    auto cucina_cover = new CucinaCover();
    App.register_component(cucina_cover);
    return {cucina_cover};

  covers:
    - name: "Cucina Cover"

