esphome:
  name: a_test_board
  platform: ESP32
  board: nodemcu-32s
  includes:
    - my_custom_component.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable captive portal
captive_portal:
# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:
# Enable ota
ota:
    
esp32_camera:
  name: Corridoio
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  resolution: 640x480
  jpeg_quality: 10

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Temperatura corridoio"
    humidity:
      name: "Umidità corridoio"
    update_interval: 60s


custom_component:
  -  lambda: |-
     auto my_custom = new MyCustomComponent();
     App.register_component(my_custom);
     return {my_custom};

cover:
  - platform: template
    name: "Cucina"
    id: cucina
    device_class: shutter
    open_action:
      - custom_component.on_start_shutter:
          shutter: up0
    close_action:
      - custom_component.on_start_shutter:
          shutter: do0
    stop_action:
      - custom_component.on_start_shutter:
          shutter: st0      
    optimistic: True
    
  - platform: template
    name: "Camera bimbe"
    id: camera bimbe
    device_class: shutter
    open_action:
      - custom_component.on_start_shutter:
          shutter: up1
    close_action:
      - custom_component.on_start_shutter:
          shutter: do1
    stop_action:
      - custom_component.on_start_shutter:
          shutter: st1      
    optimistic: True
    
  - platform: template
    name: "Camera nonna"
    id: camera_nonna
    device_class: shutter
    open_action:
      - custom_component.on_start_shutter:
          shutter: up2
    close_action:
      - custom_component.on_start_shutter:
          shutter: do2
    stop_action:
      - custom_component.on_start_shutter:
          shutter: st2      
    optimistic: True
    
  - platform: template
    name: "Bagno grande"
    id: bagno_grande
    device_class: shutter
    open_action:
      - custom_component.on_start_shutter:
          shutter: up3
    close_action:
      - custom_component.on_start_shutter:
          shutter: do3
    stop_action:
      - custom_component.on_start_shutter:
          shutter: st3      
    optimistic: True   
 
 
