esphome:
  name: sonoff
  platform: ESP8266
  board: esp01_1m  
  
  
wifi:
  ssid: "MTT_2.4"
  password: "???"
  
 # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.107
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable captive portal
captive_portal:

web_server:
  port: 80

# Enable logging
logger:
#  level: DEBUG

# Enable Home Assistant API
api:

# Enable ota
ota:
    
sensor:
  - platform: dht
    pin: GPIO3
    temperature:
      name: "Temperatura sala"
    humidity:
      name: "Umidità sala"
    update_interval: 30s
  - platform: wifi_signal
    name: "Sonoff WiFi"
    update_interval: 60s
  - platform: uptime
    name: "Sonoff Uptime"

text_sensor:
  - platform: version
    name: "Sonoff ESPHome Version"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1 
    on_press:
      then:
        - light.toggle: light_1
        
  - platform: status
    name: "Sonoff Status"

light:
  - platform: binary
    name: "Lampada"
    icon: "mdi:lamp"
    id: light_1
    output: relay_1    
    
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: yes
