esphome:
  name: esp32cam
  platform: ESP32
  board: esp32dev
  arduino_version: latest
  includes:
    - my_custom_component.h

wifi:
  ssid: "MTT_2.4"
  password: ""
  
 # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.99
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable captive portal
captive_portal:

web_server:
  port: 80

# Enable logging
logger:
#  level: DEBUG

# Enable Home Assistant API
api:

# Enable ota
ota:
    
time:
  - platform: homeassistant
    id: homeassistant_time

esp32_camera:
  name: corridoio
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  jpeg_quality: 10
  resolution: 1600x1200

sensor:
  - platform: dht
    model: AM2302
    pin: GPIO15
    temperature:
      name: "Temperatura corridoio"
    humidity:
      name: "Umidità corridoio"
    update_interval: 60s

    
switch: 
  - platform: gpio
    pin: GPIO4
    name: Luce webcam”  


binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "PIR Sensor"
    device_class: motion
  - platform: status
    name: "Webcam Status"   

    
cover:
  - platform: template
    name: "Cucina"
    id: cucina
    device_class: shutter
    optimistic: true
    open_action:
      -  lambda: return up0;
    close_action:
      -  lambda: return do0;
    stop_action:
      -  lambda: return st0;  
  

